// Demo seed data for first load
import type { Profile, GradingSystem } from '@/types'

export const DEMO_PROFILE: Profile = {
  id: 'demo-profile',
  name: 'Alex Johnson',
  institution: 'MIT',
  program: 'B.S. Computer Science',
  gradingSystemId: 'cgpa10',
  createdAt: Date.now(),
  updatedAt: Date.now(),
  semesters: [
    {
      id: 'sem-1',
      name: 'Semester 1',
      year: 2023,
      term: 'Fall',
      isCompleted: true,
      courses: [
        {
          id: 'c1-1',
          name: 'Introduction to Programming',
          code: 'CS101',
          credits: 4,
          gradingSystemId: 'cgpa10',
          notes: '',
          isZeroCredit: false,
          assessments: [
            { id: 'a1', name: 'Homework', weight: 20, score: 92, maxScore: 100 },
            { id: 'a2', name: 'Midterm', weight: 35, score: 88, maxScore: 100 },
            { id: 'a3', name: 'Final Exam', weight: 45, score: 91, maxScore: 100 },
          ],
        },
        {
          id: 'c1-2',
          name: 'Calculus I',
          code: 'MATH101',
          credits: 4,
          gradingSystemId: 'cgpa10',
          notes: '',
          isZeroCredit: false,
          assessments: [
            { id: 'a4', name: 'Quizzes', weight: 15, score: 85, maxScore: 100 },
            { id: 'a5', name: 'Midterm', weight: 35, score: 78, maxScore: 100 },
            { id: 'a6', name: 'Final Exam', weight: 50, score: 82, maxScore: 100 },
          ],
        },
        {
          id: 'c1-3',
          name: 'Physics I',
          code: 'PHYS101',
          credits: 3,
          gradingSystemId: 'cgpa10',
          notes: '',
          isZeroCredit: false,
          assessments: [
            { id: 'a7', name: 'Labs', weight: 20, score: 95, maxScore: 100 },
            { id: 'a8', name: 'Midterm', weight: 30, score: 87, maxScore: 100 },
            { id: 'a9', name: 'Final', weight: 50, score: 89, maxScore: 100 },
          ],
        },
        {
          id: 'c1-4',
          name: 'Expository Writing',
          code: 'ENG101',
          credits: 3,
          gradingSystemId: 'cgpa10',
          notes: '',
          isZeroCredit: false,
          assessments: [
            { id: 'a10', name: 'Essays', weight: 60, score: 93, maxScore: 100 },
            { id: 'a11', name: 'Final Paper', weight: 40, score: 90, maxScore: 100 },
          ],
        },
      ],
    },
    {
      id: 'sem-2',
      name: 'Semester 2',
      year: 2024,
      term: 'Spring',
      isCompleted: true,
      courses: [
        {
          id: 'c2-1',
          name: 'Data Structures & Algorithms',
          code: 'CS201',
          credits: 4,
          gradingSystemId: 'cgpa10',
          notes: '',
          isZeroCredit: false,
          assessments: [
            { id: 'b1', name: 'Problem Sets', weight: 30, score: 88, maxScore: 100 },
            { id: 'b2', name: 'Midterm', weight: 30, score: 85, maxScore: 100 },
            { id: 'b3', name: 'Final', weight: 40, score: 90, maxScore: 100 },
          ],
        },
        {
          id: 'c2-2',
          name: 'Discrete Mathematics',
          code: 'MATH201',
          credits: 4,
          gradingSystemId: 'cgpa10',
          notes: '',
          isZeroCredit: false,
          assessments: [
            { id: 'b4', name: 'Assignments', weight: 25, score: 72, maxScore: 100 },
            { id: 'b5', name: 'Midterm', weight: 35, score: 68, maxScore: 100 },
            { id: 'b6', name: 'Final', weight: 40, score: 74, maxScore: 100 },
          ],
        },
        {
          id: 'c2-3',
          name: 'Computer Organization',
          code: 'CS210',
          credits: 3,
          gradingSystemId: 'cgpa10',
          notes: '',
          isZeroCredit: false,
          assessments: [
            { id: 'b7', name: 'Labs', weight: 25, score: 91, maxScore: 100 },
            { id: 'b8', name: 'Midterm', weight: 30, score: 87, maxScore: 100 },
            { id: 'b9', name: 'Final', weight: 45, score: 93, maxScore: 100 },
          ],
        },
      ],
    },
    {
      id: 'sem-3',
      name: 'Semester 3',
      year: 2024,
      term: 'Fall',
      isCompleted: false,
      courses: [
        {
          id: 'c3-1',
          name: 'Operating Systems',
          code: 'CS301',
          credits: 4,
          gradingSystemId: 'cgpa10',
          notes: '',
          isZeroCredit: false,
          assessments: [
            { id: 'd1', name: 'Projects', weight: 40, score: 88, maxScore: 100 },
            { id: 'd2', name: 'Midterm', weight: 30, score: 82, maxScore: 100 },
            { id: 'd3', name: 'Final', weight: 30, score: null, maxScore: 100 },
          ],
        },
        {
          id: 'c3-2',
          name: 'Database Systems',
          code: 'CS315',
          credits: 3,
          gradingSystemId: 'cgpa10',
          notes: '',
          isZeroCredit: false,
          assessments: [
            { id: 'd4', name: 'Assignments', weight: 30, score: 95, maxScore: 100 },
            { id: 'd5', name: 'Project', weight: 35, score: 91, maxScore: 100 },
            { id: 'd6', name: 'Final', weight: 35, score: null, maxScore: 100 },
          ],
        },
        {
          id: 'c3-3',
          name: 'Machine Learning',
          code: 'CS350',
          credits: 4,
          gradingSystemId: 'cgpa10',
          notes: '',
          isZeroCredit: false,
          assessments: [
            { id: 'd7', name: 'Assignments', weight: 25, score: null, maxScore: 100 },
            { id: 'd8', name: 'Midterm', weight: 35, score: null, maxScore: 100 },
            { id: 'd9', name: 'Final Project', weight: 40, score: null, maxScore: 100 },
          ],
        },
      ],
    },
  ],
}

export const DEMO_CUSTOM_SYSTEM: GradingSystem = {
  id: 'custom-example',
  type: 'custom',
  name: 'Custom Scale (Example)',
  maxPoints: 5.0,
  scale: [
    { letter: 'A', minPercent: 90, maxPercent: 100, points: 5.0 },
    { letter: 'B', minPercent: 80, maxPercent: 89.99, points: 4.0 },
    { letter: 'C', minPercent: 70, maxPercent: 79.99, points: 3.0 },
    { letter: 'D', minPercent: 60, maxPercent: 69.99, points: 2.0 },
    { letter: 'F', minPercent: 0, maxPercent: 59.99, points: 0 },
  ],
}
